sudo: required
services:
  - docker

before_install :
  - docker build -t multi-docker-fibonacci-app/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true USERNAME/react-test npm test

after_success:
  - docker build -t multi-docker-fibonacci-app/multi-client ./client
  - docker build -t multi-docker-fibonacci-app/multi-nginx ./nginx
  - docker build -t multi-docker-fibonacci-app/multi-server ./server
  - docker build -t multi-docker-fibonacci-app/multi-worker ./worker

language: generic